# Generated by Django 2.2.6 on 2019-10-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('dob', models.DateField()),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('private', models.BooleanField()),
                ('bio', models.CharField(max_length=300)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
