# Generated by Django 2.2.6 on 2019-11-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
