# Generated by Django 2.2.6 on 2019-10-02 17:06

from django.db import migrations
from datetime import date

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(name="Wiggle E. Eye", username="wiggles", dob=date.today(), email="wiggl.e.i@gmail.com", password="ilovetowaggle", private=False, bio="I love to wiggle and I want everyone to know about it. Please enjoy following my journey in wiggles.").save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
