# Generated by Django 2.2.6 on 2019-11-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_body',
            field=models.IntegerField(default=0),
        ),
    ]
