# Generated by Django 2.2.6 on 2019-10-25 22:36

from django.db import migrations
from users.models import User

def create_data(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    author_user = User.objects.get(pk=1)
    author_user.post_set.create(text="guys only want one thing and it's fucking disgusting").save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
