# Generated by Django 2.2.6 on 2019-11-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retwist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retwist_original_post', to='posts.Post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retwist_post', to='posts.Post')),
            ],
        ),
    ]
