# Generated by Django 2.2.6 on 2019-12-03 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_retwist'),
    ]

    operations = [
        migrations.AddField(
            model_name='retwist',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
