# Generated by Django 2.2.6 on 2019-10-27 20:40

from django.db import migrations
from posts.models import Post

def create_data(apps, schema_editor):
    Tag = apps.get_model('posts', 'Tag')
    post = Post.objects.get(pk=1)
    post.tag_set.create(name="Harry's").save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191027_2017'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
