# Generated by Django 2.2.6 on 2019-11-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twist',
            name='tag',
            field=models.CharField(max_length=20),
        ),
    ]
