# Generated by Django 2.2.6 on 2019-11-27 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twist_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
