# Generated by Django 2.2.6 on 2019-11-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twists', '0002_auto_20191114_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='twist',
            name='followed',
            field=models.BooleanField(default=False),
        ),
    ]
