# Generated by Django 2.2.6 on 2019-11-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twists', '0003_like'),
        ('twists', '0003_twist_followed'),
    ]

    operations = [
    ]
